// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhhumkpualwbxsgfspbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoaHVta3B1YWx3YnhzZ2ZzcGJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTU0MzcsImV4cCI6MjA2MzY5MTQzN30.GlZ2d7juEAS2O8QeAsNrnPprsAWNoAk1oST2ayjQhzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);